problem = """\
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the \
first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the \
even-valued terms."""

print(problem)

# F(n) = nth Fibonacci number = F(n - 1) + F(n - 2), with F(0) = 0, F(1) = 1, F(2) = 1, F(3) = 2.
# The even-valued terms will be F(3k) for all integer k.

# F(3k + 3) = F(3k + 2) + F(3k + 1)
#          = F(3k) + 2F(3k + 1)
#          = 3F(3k) + 2F(3k - 1)
#          = 3F(3k) + 2F(3k - 2) + 2F(3k - 3)
